### ISSUE TITLE
Empire select pops up when there is already a character

### ISSUE THREAD

**Issue by MeikelLP** [MeikelLP/quantum-core-x#165]
Especially when creating a fresh instance and logging in for the first time

**Comment by uutkukorkmaz** [comment]
I guess this happens bc player's initial `Empire` value is `0`. imo, Jinno is the best empire so we could bump it up to `3`, lol. Couldn't think any better solution :)

**Comment by MeikelLP** [comment]
Oh? I thought Jinno is 0? I tried to fix it but got even more confused. Feel free to fix it^^

**Comment by uutkukorkmaz** [comment]
Perfect, I'll submit a PR by the end of today!
