### ISSUE TITLE
bug: Item duplication occurs when dropping the item.

### ISSUE THREAD

**Issue by uutkukorkmaz** [MeikelLP/quantum-core-x#191]
### What happened?

I can duplicate items by just dropping them.

### How to reproduce?

![drop-duplication-1](https://github.com/user-attachments/assets/5aceb542-4dd9-40ea-97ad-fcccd8667a6d)

### OS Platform

Windows

**Comment by MeikelLP** [comment]
I think this should be backed by a test to avoid regression
