### ISSUE TITLE
bug: item duplication occurs when moving the item in the inventory.

### ISSUE THREAD

**Issue by uutkukorkmaz** [MeikelLP/quantum-core-x#192]
### What happened?

I can duplicate items by just moving them in the inventory. It's a bit tricky but....

### How to reproduce?

1. Get yourself a beautiful, shining `Sword +9` or any item you wish with the following command: `/item 19`.
2. Move your legendary rare item within your inventory.
   ![move-duplication-1](https://github.com/user-attachments/assets/0fc5c1b0-e6d3-4c7b-93b1-187d07df3b55)
   
   2.1. Take a look at your `Items` table in the database, and you’ll see a shocking view like the one below.
   ![move-duplication-db](https://github.com/user-attachments/assets/ca132717-7c48-42c0-80ed-702fcd4799f7)

   2.2. Logout and login again. Nothing happens... Hmm, suspicious.

3. Stop the game server, flush the cache, and restart the game server.

4. Login and open your inventory.
   ![move-duplication-result](https://github.com/user-attachments/assets/dba73e24-31a7-41ee-a56e-f99319e916b9)

5. Notice that your legendary rare `Sword +9` is now just a simple common `Sword +9`.

### OS Platform

Windows

**Comment by uutkukorkmaz** [comment]
It gets really interesting when you move the item to the second page of the inventory.

**Comment by MeikelLP** [comment]
This should be backed by a test to avoid regression
