### ISSUE TITLE
bug: ground items won't disappear until the server is restarted.

### ISSUE THREAD

**Issue by uutkukorkmaz** [MeikelLP/quantum-core-x#193]
### What happened?

I dropped an item and wait, one eternaty later it was still there.

### OS Platform

Windows

**Comment by MeikelLP** [comment]
This could also be a (missing) feature 👀

**Comment by uutkukorkmaz** [comment]
Fully supporting your suggestion. Then I shall create an issue to track this rewrite with a robust user story. :)
