### ISSUE TITLE
Empire logic wrong

### ISSUE THREAD

**Issue by NoFr1ends** [MeikelLP/quantum-core-x#25]
Currently the player empire is stored at the account which might be the wrong location.
Thinking about how the official server run it should probably be stored somewhere in the game database to allow different empires on different game servers.

Also currently there's a bug in [EmpireHandler.cs#L25](https://github.com/MeikelLP/quantum-core-x/blob/4c894b56df77ec68b020a1c4af27f084621c38d7/Executables/Game/PacketHandlers/Select/EmpireHandler.cs#L25) as it tries to access the non existent table `accounts` inside the `game` database.

**Comment by MeikelLP** [comment]
Resolved in #49
